version: "3"

services:

  account-service:
    image: all-in-one/account-service
    links:
      - rabbitmq
    ports:
      - "3311:3000"
    environment:
      - ACCOUNT_DATABASE_URL=postgresql://postgres:helloworld@localhost:5432/account?schema=accounts
      - AT_JWT_SECRET=helloworldhelloworldhelloworld
      - AT_JWT_EXPIRES_IN=900
      - RT_JWT_SECRET=helloworldhelloworldhelloworld
      - RT_JWT_EXPIRES_IN=604800
      - JWT_SALT=12
      - RABBITMQ_HOST=rabbitmq
    networks:
      - private_network
    depends_on:
      - rabbitmq
      - postgres
      - redis

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - private_network

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=12345
    ports:
      - '3000:3000'
    networks:
      - private_network
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/posgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: helloworld
    ports:
      - '5432:5432'
    networks:
      - private_network
  redis:
    image: redis
    command: /bin/sh -c "redis-server --requirepass helloworld"
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    networks:
      - private_network


  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - './data/rabbitmq_data:/bitnami/rabbitmq/mnesia'
    networks:
      - private_network

  tcpdump:
    image: nicolaka/netshoot
    depends_on:
      - rabbitmq
      - account-service
    command: tcpdump -i eth0 -w /data/nginx.pcap
    volumes:
      - $PWD/data:/data
    networks:
      - private_network

networks:
  private_network:
    driver: bridge

